appraise "legacy" do
  gem "mysql", "2.9.1"
  gem "mysql2", "0.3.18"
  gem "activerecord-mysql2-adapter", "0.0.3"
  gem "pg", "0.18.2"
  gem "sqlite3", "1.3.10"
  gem "activerecord", "3.0.0"
end

# appraise "java-legacy" do
#   gem "activerecord-jdbc-adapter"
# end

appraise "activerecord-5.0" do
  gem "activerecord", "~>5.0"
end

appraise "activerecord-5.1" do
  gem "activerecord", "~>5.1"
end

appraise "activerecord-5.2" do
  gem "activerecord", "~>5.2"
end

